
services:
  db:
    container_name: protoapp-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xyzzy

